[package]
name = "shrm-dao-proposals"
version = "0.1.0"
authors = ["SweetieRick", "Tarnadas"]
edition = "2021"

[dependencies]
serenity = "0.10"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.5", features = [ "runtime-tokio-rustls" ] }
dotenv = "0.15.0"